#:schema node_modules/wrangler/config-schema.json

name = "letterbox"
main = "src/index.ts"
compatibility_date = "2022-12-24"
usage_model = "unbound"


route = { pattern = "letterbox-api.cyberjake.xyz", custom_domain = true }

vars = {LoginMinutes = 10}

[[r2_buckets]]
binding = 'R2'
bucket_name = 'letterbox'
preview_bucket_name = 'letter-box-dev'


[[ d1_databases ]]
binding = "DB"
database_name = "letterbox-prod"
database_id = "3b20ad3e-e838-48e9-8150-f7a58254c0d3"
preview_database_id = "4f1f55a7-3ca9-4447-b992-4df098c4fd67"